<?php

use Illuminate\Database\Seeder;

class ReviewItemsSeeder extends Seeder
{
    public function runarray()
    {
        $data = arrayarray(
        	array(1, 'Placa de identificación de la torre array(en concordancia con API 4F,  Fabricante, licencia del fabricante, modelo, serie, capacidades de carga, PSL, entre otros', 1),
			array(2, 'Inspecciones NDT categoría III y categoría IV actualizadas array(documentadas y en concordancia con API RP4G)', 1),
			array(3, 'Verificación de la correcta operación de todas las poleas de la corona', 1),
			array(4, 'Certificación de calibración de todas las poleas, de acuerdo con el API 9B', 1),
			array(5, 'La corona dispone de los bloques de madera protectores de impactos', 1),
			array(6, 'Las poleas de la corona cuentan con los respectivos protectores instalados, para prevenir la salida del drilling line', 1),
			array(7, 'Verificación condición de las barandas y rodapiés de la corona', 1),
			array(8, 'Adecuada iluminación de la torre array(Todas las lámparas operativas)', 1),
			array(9, 'Lámparas con eslingas de seguridad en buen estado y confiables', 1),
			array(10, 'Correcta operación de la lámpara de destello de la corona array(Acorde al reglamento aeronáutico Colombiano -RAC)', 1),
			array(11, 'Sistema de protección contra Rayos en buen estado, bien instalado y en concordancia con la NTC-4552', 1),
			array(12, 'Trabajadero de tubería y barandas en buen estado', 1),
			array(13, 'Sistema de seguridad contra caída del trabajadero de tubería operativo e inspeccionado', 1),
			array(14, 'Lengüeta del trabajadero, con aseguramiento secundario, ¿las eslingas son de la capacidad acorde al peso de la lengüeta?', 1),
			array(15, 'Dispositivo de escape desde el trabajadero operativo, certificado y bien instalado', 1),
			array(16, 'Los trinchos del trabajadero con espaciamiento de acuerdo con el tamaño de tubería y BHA a operar', 1),
			array(17, 'Sistema antideslizante seguro en los trinches del trabajadero', 1),
			array(18, 'Winche del trabajadero en buen estado y probado', 1),
			array(19, 'Certificados de inspección NDT del trabajadero de casing', 1),
			array(20, 'Cable del winche del trabajadero de tubería en buen estado', 1),
			array(21, 'Condición general del trabajadero de casing', 1),
			array(22, 'Trabajadero de casing de altura ajustable', 1),
			array(23, 'Winche del trabajadero de casing, en buen estado', 1),
			array(24, 'Cable del winche del trabajadero de casing en buen estado', 1),
			array(25, 'Protección por caída libre del trabajadero de casing operativa', 1),
			array(26, 'Correcta operación del sistema de protección Anticolisión array(Twin Stop, Posi Stop, EDS, Crown-0-Matic)', 1),
			array(27, 'Protección de seguridad para no impactar el trabajadero de tubería, Operativo y probado', 1),
			array(28, 'Escalera de ascenso a la torre en buen estado', 1),
			array(29, 'Verificación del equipo de seguridad de subida y la línea de seguridad de la escalera de la torre', 1),
			array(30, 'Verificación de la eslinga de izar la torre, en buen estado', 1),
			array(31, 'Registre fecha de fabricación de la eslinga y fecha última inspección NDT', 1),
			array(32, 'Verificación de los pines en buen estado e inspección NDT vigente', 1),
			array(33, 'Pines instalados adecuadamente', 1),
			array(34, 'Todos los Pines con Chaveta de seguridad instalados', 1),
			array(35, 'Dispositivo de escape desde el trabajadero, correctamente instalado', 1),
			array(36, 'Señales de advertencia al ascender a la torre', 1),
			array(37, 'Revisión general de pines, pernos y tuercas aseguradas en el mástil array(Programa Drops)', 1),
			array(38, 'Verificación string up correcto del cable conforme corresponde al arreglo de las poleas de la corona array(Que no existan líneas cruzadas)', 1),
			array(39, 'Se verifico que no existieran piezas sueltas u o elementos susceptibles de caer desde el Mástil', 1),
			array(40, 'Se verifico e inspeccionó ángulos, vigas ,ríeles, guías, correderas, contrapesas, soldaduras, puntos críticos donde mayor fricción tiene el cable de perforación, puntos de apoyo de rodamientos de las poleas, holgura entre pernos y agujeros array(desgastes), corrosión, fisuras, calentamientos anormales o golpes', 1),
			array(41, 'Se verificó adecuada condición del soporte del service loop del Top Orive', 1),
			array(42, 'Anclaje de los retráctiles para ascenso a la corona y el área del trabajadero de tubería, inspeccionados y certificados para 5.000 Lbs', 1),
			array(43, 'Verificación de uso de tuercas de seguridad en soportes de la reaction beam del Top Orive', 1),
			array(44, 'Pintura superior de la torre, en concordancia con el RAC', 1),
			array(45, '¿Se observa alguna modificación al diseño original de la torre, está debidamente documentado el cambio?', 1),
			array(46, 'Placa de identificación de la subestructura array(en concordancia con API 4F, Fabricante, # de licencia, modelo,  serie, capacidades de carga, PSL, entre otros)', 2),
			array(47, 'Inspecciones NDT categoría III y categoría IV actualizadas {documentadas v en concordancia con API R P4G)', 2),
			array(48, 'Todos los elementos estructurales de la subestructura instalados', 2),
			array(49, 'El área debajo del malacate dispone de rejilla de seguridad para prevención de caída de objetos al contrapozo', 2),
			array(50, 'Instalaciones eléctricas tipo XP y en buenas condiciones', 2),
			array(51, 'Lámparas de la subestructura tipo XP, en buen estado ', 2),
			array(52, 'Lámparas con eslingas de seguridad en buen estado y confiables', 2),
			array(53, 'Plataforma para el Nipple Up de las BOPs seguro, con barandas en buen estado', 2),
			array(54, 'Retráctiles certificados y probados', 2),
			array(55, 'Soportes de los retractiles inspeccionados y certificados para 5.000 Lbs', 2),
			array(56, 'Verificación de correcta instalación de los pines, todos con su respectiva chaveta de seguridad', 2),
			array(57, '¿Todos los pasadores de la subestructura disponen de Inspección NDT vigente?', 2),
			array(58, 'Revisión general de pines, pernos y tuercas. aseguradas en la subestructura array(Programa Drops)', 2),
			array(59, 'Verificar que no existieran piezas sueltas u o elementos susceptibles de caer desde la subestructura array(Programa Drops)', 2),
			array(60, 'Verificar condición de ángulos, vigas, rieles, guías, contrapesas, soldaduras, holguras entre pernos y agujeros {desgastes), corrosión, fisuras, calentamientos anormales o golpes', 2),
			array(61, 'Se dispone de rejilla de seguridad en buen estado, en el área del contrapozo', 2),
			array(62, '¿Se dispone de las bandejas ecológicas o sistema de descarga de lodo, al tanque Flow line?', 2),
			array(63, 'Condición general del BOP Handling System', 2),
			array(64, 'Inspección NDT vigente del sistema de izaje del', 2),
			array(65, 'Verificación de registros de mantenimiento de los winches de izar las BOP \'s, sus rodillos, operadores remotos y rieles', 2),
			array(66, 'Verificar correcta operación deI sistema hidráulico para levantar la subestructura array(Válvula de control, mangueras, acoples, cilindros hidráulicos sin fugas ni ruidos anormales)', 2),
			array(67, 'Verificar correcta operación de la HPU requerida para operar los cilindros hidráulicos de levantar la torre array(se debe contar con dos bombas hidráulicas, una de accionamiento eléctrica y una de accionamiento con motor diésel)', 2),
			array(68, 'Marca y tipo de bloque viajero', 3),
			array(69, 'Verificar registros de inspección NDT categoría II y categoría IV vigentes', 3),
			array(70, 'Verificar registros de mantenimiento recientes', 3),
			array(71, 'Verificar PSL del bloque viajero, concordante con el PSL de la corona', 3),
			array(72, 'Verificar condición general de las poleas', 3),
			array(73, 'Verificar ajustes de los rodamientos, mediante prueba de rodadura y bamboleo', 3),
			array(74, 'Guardas de seguridad en buenas condiciones y bien aseguradas', 3),
			array(75, 'Verificar que todas las tuercas y pasadores dispongan de adecuado aseguramiento secundario', 3),
			array(76, 'Verificar estado de las graseras y líneas de lubricación, asegurando que todos los rodamientos reciban la grasa', 3),
			array(77, 'Placa del bloque instalada en su cuerpo', 3),
			array(78, 'Verificar correcta operación del tope superior de carrera y tope inferior de carrera', 3),
			array(79, 'Verificar adecuada operación del seguro de giro del gancho perro', 3),
			array(80, 'Verificar que el gancho esta adecuadamente centrado con respecto a la mesa rotaria', 3),
			array(81, 'Verificó correcta posición del bloque viajero respecto del top drive', 3),
			array(82, 'La torre cuenta con dispositivo para colgar el bloque viajero', 3),
			array(83, 'Verificar correcto String Up del Drilling Line', 3),
			array(84, 'Verificar certificados de inspección categoría III y categoría IV vigentes, del malacate y su sistema de frenos', 4),
			array(85, 'Verificar registros recientes del mantenimiento preventivo del malacate y record de horas, desde el ultimo overhaul', 4),
			array(86, 'Verificar adecuado diámetro del tambor del malacate', 4),
			array(87, 'Verificar condición de desgaste del drum jacket', 4),
			array(88, 'Verificar juego radial de los rodamientos', 4),
			array(89, 'Verificar juego axial de los rodamientos principales', 4),
			array(90, 'Verificar adecuada condición de todas las guardas de seguridad', 4),
			array(91, 'Verificar condición de operación del clutch de alta y clutch de baja', 4),
			array(92, 'Verificar correcto suministro de aire al malacate array(120 PSI)', 4),
			array(93, 'Verificar condición de la trasmisión de potencia por cadena array(cadenas de transmisión, sprockets, cuñas, ejes, rodamientos, palancas)', 4),
			array(94, 'Verificar condición del sistema de freno de bandas y los rim brakes', 4),
			array(95, 'Verificar condición del sistema de freno de emergencia array(Crown-0- Matic, Posi Stop, Twin Stop, EDS o equivalente)', 4),
			array(96, 'Verificar la condición de las áreas de circulación en torno del malacate', 4),
			array(97, 'Verificar correcta alineación de los motores eléctricos de tracción, con el eje de entrada de potencia del malacate', 4),
			array(98, 'Efectuar revisión Interna a los motores eléctricos de tracción del malacate array(bobinas de campo, rotor, colector, porta escobillas, escobillas, cableado en general)', 4),
			array(99, 'Verificar los puntos de bloqueo de los motores eléctricos de tracción del malacate', 4),
			array(100, 'Verificar instalación a tierra de los motores de tracción y los Blowers', 4),
			array(101, 'Verificar correcta operación de los motores de tracción del malacate', 4),
			array(102, 'Verificar correcta operación de los Blowers de los motores de D.C.', 4),
			array(103, 'Verificar correcta operación del sistema de lubricación del malacate', 4),
			array(104, 'Verificar correcta operación de todos los puntos de lubricación', 4),
			array(105, 'Realizar giro en los dos sentidos del tambor, sin ruidos, temperaturas o vibraciones anormales', 4),
			array(106, 'Verificar correcta operación de todos los mandos de la consola del perforador', 4),
			array(107, 'Verificar correcta operación de toda la instrumentación del malacate ésta debe estar certificada por parte de un instrumentista idóneo', 4),
			array(108, 'Verificar condición del set de rollers de caucho y los kickers', 4),
			array(109, 'Verificar condición del drilling line, de acuerdo con API RP9B', 4),
			array(110, 'Verificar condición de los wear plates', 4),
			array(111, 'Verificar adecuado anclaje del drilling line al drum del malacate', 4),
			array(112, 'Probar las diferentes asignaciones del malacate con el SCR1, SCR2, SCR3,en las posiciones DRILLING.', 4),
			array(113, 'Probar el shut down del malacate desde la consola del perforador', 4),
			array(114, 'Verificar adecuada operación de los mandos de la trasmisión del malacate Low·Low, Low·High, High·High .', 4),
			array(115, 'Verificar adecuada operación de los Cat Heads', 4),
			array(116, 'Verificar adecuada instalación del freno auxiliar Elmagco Baylor o Eaton', 4),
			array(117, 'Verificar correcta operación del freno auxiliar, con el peso de la polea viajera y del Top Orive', 4),
			array(118, 'Verificar adecuado arrollamiento del drilling line sobre el tambor del malacate', 4),
			array(119, 'Inspección NDT categoría III y categoría IV, vigentes', 5),
			array(120, 'Condición general de la estructura del ancla', 5),
			array(121, 'Condición de todos los pernos y tuercas del ancla', 5),
			array(122, 'Condición de ajuste de todas las tuercas', 5),
			array(123, 'Cable de perforación bien instalado', 5),
			array(124, 'La celda de transmisión está operativa', 5),
			array(125, 'condición de los bronces del ancla', 5),
			array(126, 'El GAP de la celda es correcto', 5),
			array(127, 'condición general de la celda de tensión array(garrapata)', 5),
			array(128, 'Chavetas de seguridad de pasador superior e inferior en su lugar', 5),
			array(129, 'Manguera y celda sin fugas de aceite hidráulico', 5),
			array(130, 'Condición del rodamiento central del ancla', 5),
			array(131, 'Guarda protectora sobre el tambor del ancla', 5),
			array(132, 'Registros de ultimo mantenimiento del ancla', 5),
			array(133, 'Verificar Inspección NDT categoría III y categoría IV, vigentes', 6),
			array(134, 'Condición general de la mesa rotaria a área aledaña', 6),
			array(135, 'Condición de todos los pernos, tuercas y pasadores de la mesa', 6),
			array(136, 'Condición general del aceite y engrase de la mesa rotaria', 6),
			array(137, 'Operación sin ruidos anormales ni vibraciones de la mesa', 6),
			array(138, 'Nivelación y adecuado soporte de la masa', 6),
			array(139, 'Condición del Backlash de la transmisión de la mesa', 6),
			array(140, 'Condición de la transmisión de potencia hacia la mesa', 6),
			array(141, 'Piso antideslizante en torno de la mesa', 6),
			array(142, 'Áreas de la mesa libres de agujeros, puntos de tropiezo o superficies lisas', 6),
			array(143, 'Reportes de los últimos mantenimientos, en orden', 6),
			array(144, 'La operación hacia la derecha y en reversa es normal', 6),
			array(145, 'Los seguros Perros están plenamente operativos', 6),
			array(146, 'Barandas de seguridad con rodapiés, acordes a la Res. 01409 y sin cargas externas', 6),
			array(147, 'Barandas con seguros para prevenir su eventual caída', 6),
			array(148, 'Bolsillos de las barandas sin corrosión, sin fisuras, que permitan adecuada estabilidad a las barandas', 6),
			array(149, 'Verificar disponibilidad de los tres juegos de Insert Bowls array(#1, 2 y 3), para el master Bushing', 6),
			array(150, 'Verificar condición e inspecciones NDT del master Bushing de la rotaría', 6),
			array(151, 'Verificar condición del economizador de lodo array(Mud bucket)de acuerdo al diámetro de la tubería que se utilizará', 6),
			array(152, 'Verificar registros de inspecciones NDT categoría III y categoría IV', 7),
			array(153, 'Verificar Dossier del Top Orive y los registros de mantenimientos preventivo', 7),
			array(154, 'El PSL del Top Orive, es acorde a las exigencias del pozo', 7),
			array(155, 'Rotación a la derecha e izquierda', 7),
			array(156, 'Sacar y meter los Links array(Link Tilt)', 7),
			array(157, 'Prueba del sistema de flotación array(Float)', 7),
			array(158, 'Abrir y cerrar la lower well control valve hidráulica', 7),
			array(159, 'Prueba de rotación del tornamesa a derecha e izquierda', 7),
			array(160, 'Prueba de correcta operación del seguro del tornamesa', 7),
			array(161, 'Prueba de abrir y cerrar mordazas del Pipe Handler', 7),
			array(162, 'Verificar que se disponga de los juegos de link para operar, para operaciones de corrida, de revestimiento y cementación', 7),
			array(163, 'Prueba de correcta operación de la grabber sobre un tool joint de6 3/4 0D', 7),
			array(164, 'Verifico correcta operación del wash pipe', 7),
			array(165, 'Prueba del sistema de freno de disco del motor eléctrico, sin fucas de hidráulico.', 7),
			array(166, 'Probar sistema counter', 7),
			array(167, 'Verificar adecuado stock de saber subs de repuesto para el T.D.', 7),
			array(168, 'Probar recorrido a lo largo de la torre sin ninguna interferencia con el trabajadero ni otro elemento', 7),
			array(169, 'Verificar correcto ajuste entra la manguera del stand pipe y el gooseneck', 7),
			array(170, 'Verificar temperaturas de operación del gearbox', 7),
			array(171, 'Verificar correcta operación de todos los mandos y los dos  shut downs de la consola', 7),
			array(172, 'Verificar presión de precarga de los acumuladores de presión del top drive', 7),
			array(173, 'Verificar correcta operación de todas las electroválvulas del sistema robótico', 7),
			array(174, 'Equipo sin fugas de aceite', 7),
			array(175, 'Equipo sin ruidos ni vibraciones anormales', 7),
			array(176, 'Condición de los motores principales', 7),
			array(177, 'Correcto funcionamiento del blower', 7),
			array(178, 'Presión de aceite de lubricación normal array(80PSI)', 7),
			array(179, 'Presiones del sistema hidráulico normales array(2200 PSI)', 7),
			array(180, 'Instrumentación en buen estado y funcionando array(verificar indicador de torque e indicador de RPM\'s)', 7),
			array(181, 'Condición del service loop eléctrico', 7),
			array(182, 'Condición del loop hidráulico', 7),
			array(183, 'Verificar adecuado amarre de los services Loop ', 7),
			array(184, 'Verificación de que todos los tomillos estén asegurados con alambre de seguridad', 7),
			array(185, 'Guardas de seguridad de partes móviles adecuadas', 7),
			array(186, 'Verificar condición XP del sistema eléctrico del Top Drive', 7),
			array(187, 'Sistema de puesta a tierra instalado adecuadamente y en concordancia con el RETIE ', 7),
			array(188, 'Señalización de seguridad adecuada, legible y suficiente', 7),
			array(189, 'Verificar correcta operación de las dos unidades hidráulicas array(HPU#1 y #2)', 7),
			array(190, 'Verificar correcta operación del breaker del top drive', 7),
			array(191, 'Correcta operación del VFD del top drive', 7),
			array(192, 'El VFD dispone de deshumidificador', 7),
			array(193, 'Correcta operación del sistema de refrigeración del VFD', 7),
			array(194, 'Condición de los cables de potencia y control, desde el VFO hasta el T.D.', 7),
			array(195, 'Condición de la caseta del VFD array(Ordenada, aseada. sin goteras, chapa antipánico y cierre automático)', 7),
			array(196, 'Verificar correcta alineación del Top Drive, con el centro del pozo, de acuerdo con el API 8C', 7),
			array(197, 'Realizar Inspección DROP\'s, antas de operar al Top Drive', 7),
			array(198, 'Verificar correcta operación de todas las protecciones del Top Drive', 7),
			array(199, 'Verificar inspecciones NDT categoría III y categoría IV, vigentes', 8),
			array(200, 'Verificar el Dossier con toda la información técnica y los registros de mantenimiento de la PULDM', 8),
			array(201, 'Condición general de la PULDM', 8),
			array(202, 'Condición de orden y aseo de la unidad', 8),
			array(203, 'Condición de ajuste de todos los pasadores y tuercas de la PULDM', 8),
			array(204, 'Verificar normal operación de la unidad, desde el operador remoto', 8),
			array(205, 'Verificar normal operación de la unidad, desde el panel de control, en el piso', 8),
			array(206, 'Probar los tres array(3) Shut', 8),
			array(207, 'Verificar que, en cada cuadrilla, se disponga de personal capacitado para la operación de la PULDM', 8),
			array(208, 'Realizar pruebas de carga de la unidad, con diferentes herramientas de perforación', 8),
			array(209, '¿El personal conoce los límites técnicos de la PULDM?', 8),
			array(210, 'La PULDM, cuenta con todas las guardas de seguridad Instaladas', 8),
			array(211, 'La unidad se encuentra debidamente aterrizada', 8),
			array(212, 'El área de caída de objetos en torno de la PULDM se encuentra debidamente aislada', 8),
			array(213, 'El sistema eléctrico de la PULDM es a prueba de explosión', 8),
			array(214, 'Verificar condición del cable o la cadena de tracción del Skate', 8),
			array(215, 'Verificar operación sin fugas, vibraciones ni ruidos anormales', 8),
			array(216, 'Verificar adecuado stock de repuestos en bodega, para la PULDM', 8),
			array(217, 'Verificar adecuada operación de los Pipe Racks hidráulicos', 8),
			array(218, 'Adecuado soporte de los skids y nivelación correcta', 9),
			array(219, '¿El área de circulación en derredor de las bombas, es seguro?', 9),
			array(220, 'Encendido automático centrifuga de precarga', 9),
			array(221, 'Encendido automático centrifuga de refrigeración de pistones', 9),
			array(222, 'Bandeja o dique ecológico disponible', 9),
			array(223, 'Verificar eficiencia sistema de refrigeración de pistones', 9),
			array(224, 'Verificar Nivel y temperatura del agua de refrigeración de pistones adecuado', 9),
			array(225, 'Verificar   encendido   automático de la bomba de lubricación de la trasmisión', 9),
			array(226, 'Verificar precarga dámper de descarga', 9),
			array(227, 'Precarga dámper de succión', 9),
			array(228, 'Condición filtros de succión y descarga', 9),
			array(229, 'Condición de las Reset relief valves  ajustadas de acuerdo con el diámetro de los liners', 9),
			array(230, 'Condición líneas de descarga de 2', 9),
			array(231, 'Tuercas y pernos de acuerdo con API 6A Y RP 54', 9),
			array(232, 'Condición de los Power End', 9),
			array(233, 'Condición de los desfogues array(Respiraderos) de los Power End de las bombas', 9),
			array(234, '¿El nivel y aspecto del aceite del Power End, es bueno?', 9),
			array(235, 'Condición de los Fluid End y sus componentes array(liners, pistones, asientos, válvulas, resortes, Insertos, ejes de pistón, grapas y extensión rods, entre otros)', 9),
			array(236, 'Condición guardas de seguridad', 9),
			array(237, 'Guayas de seguridad correctamente construidas e instaladas', 9),
			array(238, 'Instrumentación de la bomba operativa y certificada', 9),
			array(239, 'Fugas de aceite u otros fluidos', 9),
			array(240, 'Prueba hidrostática a baja presión array(300 a 500 Psi.), circulando al tanque de succión', 9),
			array(241, 'Prueba hidrostática a alta presión array(1.500, 3.000 Psi y 4.500 psi.) de acuerdo con el diámetro de los liners', 9),
			array(242, 'Verificar condición Vibrator Hoses', 9),
			array(243, 'Verificar Integridad de las líneas de succión', 9),
			array(244, 'Condición del Stand Pipe de descarga de las bombas de lodo', 9),
			array(245, 'Correcto anclaje de líneas de descarga de 2', 9),
			array(246, 'Inclinación de las líneas de descarga hacia los tanques de lodo array(tipo Self Drain)', 9),
			array(247, 'Estanqueidad y aseguramiento de las líneas de descarga de 3 array(desde la relief valve hacia los tanques de lodo)', 9),
			array(248, 'Condición de las gate valves de 2 y 5 del manifold de descarga de las bombas', 9),
			array(249, 'Sistema de puesta a tierra de cada bomba de lodo', 9),
			array(250, 'Condición general de los motores eléctricos de la bomba', 9),
			array(251, 'Operación sin ruidos, sobrecalentamientos ni vibraciones anormales', 9),
			array(252, 'Iluminación adecuada del área', 9),
			array(253, 'Información técnica disponible en el equipo array(manuales de servicio, operación y mantenimiento)', 9),
			array(254, 'Válvula de drenaje de condensados en el cárter del Power End', 9),
			array(255, 'Registros recientes de calibración de los rodamientos y ajuste de los Cross Heads', 9),
			array(256, 'Registros recientes de inspección NDT de las partes del Fluid end de las bombas', 9),
			array(257, 'Verificar sistema de levante de partes de los fluid end deben contar con inspección NDT vigente', 9),
			array(258, 'Verificar condición de la herramienta utilizada para cambio de pistones, asientos y liners entre otros', 9),
			array(259, 'Correas de transmisión de potencia en buen estado', 9),
			array(260, 'Verificar correcta operación de las centrífugas de precarga de las bombas de lodo', 9),
			array(261, 'Se dispone de manifold de succión, que permita alimentar las bombas con cualquiera de las centrífugas de precarga', 9),
			array(262, 'Se realizó prueba de circulación con las bombas, a través de choke manual, para confirmar capacidad de bombeo de cada una de ellas', 9),
			array(263, 'Inspección NDT categoría III y categoría IV, vigentes array(NDT con luz negra y ultrasonido)', 10),
			array(264, 'Verificar registros de inspección NDT y últimos mantenimientos realizados a válvulas y uniones de golpe del Stand Pipe', 10),
			array(265, 'Verificar condición general del stand pipe', 10),
			array(266, 'Stand pipe sin fucas de ningún tipo', 10),
			array(267, 'Condición de todos las Vibrator hoses y rotary hoses', 10),
			array(268, 'Inspección NDT de las vibrator hoses y rotary hoses array(inspección visual, NDT a las áreas termínales, Boroscopía, prueba hidrostática a la W.P)', 10),
			array(269, 'El stand pipe se encuentra anclado de manera adecuada array(Anclajes máximo cada 25 Ft.)', 10),
			array(270, 'Verificar que las uniones de golpe y demás accesorios del stand pipe, soporten presiones iguales o mayores a la W.P del Stand Pipe', 10),
			array(271, 'El código de colores está establecido array(Cada unión de golpe, con los colores definidos internacionalmente, de acuerdo con la figura de cada unión)', 10),
			array(272, 'Las uniones de golpe cuentan con guayas anti-látigo debidamente instaladas', 10),
			array(273, '¿Hay algún accesorio del stand pipe Home Made?', 10),
			array(274, '¿La línea del stand pipe es de tipo SMLSS?', 10),
			array(275, 'Se dispone de gate valve antes y después de cada vibrator hose de salida do las bombas do lodo', 10),
			array(276, 'La línea del stand pipe está pintada de rojo y señalizada', 10),
			array(277, 'Verificar registros de mantenimiento e inspección de las shakers', 11),
			array(278, 'Verificar condición general de cada shaker array(sin corrosión, plenamente operativas, bien niveladas)', 11),
			array(279, 'Verificar orden y limpieza generales del área de las shakers', 11),
			array(280, 'Verificar condición XP de toda la instalación eléctrica de las shakers', 11),
			array(281, '¿Las compuertas del circuito de lodo, están plenamente operativas?', 11),
			array(282, 'Verificar adecuada operación de sistemas de inclinación de canastas', 11),
			array(283, 'Verifica condición de todos los empaques y sellos de las shale shakers', 11),
			array(284, 'Verificar adecuada instalación y ajuste de las mallas de cada shaker', 11),
			array(285, 'Verificar adecuada instalación del SPT en cada una de las shakers', 11),
			array(286, 'Verificar adecuado ajuste de los motores vibradores', 11),
			array(287, 'Verificar correcto sentido de giro de los motores vibradores de las shakers', 11),
			array(288, 'Verificar las unidades de aceleración G, en cada una de las shakers', 11),
			array(289, 'Verificar condición de los resortes o los Rubbert Mounts de cada canasta', 11),
			array(290, 'Verificar ventilación adecuada en el área de las shakers', 11),
			array(291, 'Verificar protección de las aberturas de las bandejas de descarga', 11),
			array(292, 'Verificar adecuada operación de los desviadores de flujo hacia cada shaker', 11),
			array(293, 'Verificar que el Sand Trap, se encuentre limpio y disponga de compuerta adecuada para su limpieza', 11),
			array(294, 'Iluminación tipo XP disponible array(clase I Div.I)', 11),
			array(295, 'Provisión de iluminación adecuada array(Mínimo 150 lux)', 11),
			array(296, '¿El área de trabajo segura, libre de puntos de tropiezo o de caídas?', 11),
			array(297, 'El área de trabajo segura, con cubierta, con barandas de seguridad, ¿rodapiés?', 11),
			array(298, 'Área de circulación en torno de las shakers, segura, pisos en buen estado, sin huecos, ¿ni puntos de tropiezo?', 11),
			array(299, '¿El Possum Belly cuenta con suficiente capacidad para manejar el caudal máximo del pozo?', 11),
			array(300, '¿El Possum Belly cuenta con boquillas para mejorar prevenir decantación de sólidos?', 11),
			array(301, 'Verificar sistema de bloqueo de las shakers array(EMN)', 11),
			array(302, 'Se realizó prueba operativa de cada uno de los embudos, para verificar su desempeño', 11),
			array(303, 'Verificar estanqueidad en las líneas de suministro y retorno de lodo del Desander y del Desilter', 11),
			array(304, 'Verificar condición de la Shaker del Mud Cleaner', 11),
			array(305, 'Verificar condición de los conos del Desander', 11),
			array(306, 'Verificar condición de los conos del Desilter', 11),
			array(307, 'Verificar adecuada operación del Mud Cleaner', 11),
			array(308, 'Inspección NDT Cat. III y CAT IV, vigentes array(Inspección de espesores de pared, con ultrasonido, a paredes del tanque y líneas de circulación)', 12),
			array(309, 'Condición general de los tanques array(Capacidad, versatilidad, orden, aseo del área)', 12),
			array(310, 'Condición de todas las líneas de circulación', 12),
			array(311, 'Condición de las válvulas de control de flujo array(Válv. Mariposa, válvulas submarinas, válvulas de cortina)', 12),
			array(312, 'Verificar capacidad de la canal de circulación, acorde al máximo volumen de lodo', 12),
			array(313, 'Verificar que TODOS los artefactos eléctricos, se encuentren debidamente conectados al SPT, tal como lo establece el RETIE', 12),
			array(314, 'Sistema eléctrico XP, acorde al API RP500', 12),
			array(315, 'Condición general del sistema de iluminación acorde con API RP500 y Retilap', 12),
			array(316, '¿Hay un dispositivo para bloquear la fuente de poder de los agitadores en caso de que se deba entrar a los compartimientos de los tanques?', 12),
			array(317, 'Condición de todos los sellos de caucho, de compuertas, acoples entre tanques, líneas de circulación entre otros', 12),
			array(318, '¿Se realizó prueba de estanqueidad de los tanques de lodo?', 12),
			array(319, 'Verificar condición general de los techos de los tanques', 12),
			array(320, '¿Las líneas de vida se encuentran debidamente instaladas?', 12),
			array(321, 'Guardas de seguridad debidamente instaladas, sobre acoples de agitadores, ventiladores de motores eléctricos, correas y centrifugas', 12),
			array(322, 'Áreas de circulación seguras, sin huecos, despejadas, ¿demarcadas?', 12),
			array(323, 'Barandas de al menos 1.00 Mts. De altura y resistencia superior a 200 Lbs. ¿De carga lateral?', 12),
			array(324, 'Barandas de seguridad libres de carga', 12),
			array(325, 'Barandas de seguridad con sus respectivos rodapiés', 12),
			array(326, 'Se dispone de compuerta de acceso a cada compartimiento, con su respectiva escalera', 12),
			array(327, '¿Las compuertas de acceso se encuentran debidamente identificadas?', 12),
			array(328, 'Verificar integridad de las centrifugas de lodo en general', 12),
			array(329, 'Verificar operación de centrifugas y motores eléctricos, sin ruidos ni vibraciones anormales', 12),
			array(330, 'El diseño de los tanques es acorde al API 13c array(En cascada)', 12),
			array(331, '¿Las líneas de succión de las bombas de lodo, cuentan con manifold que permita utilizarlas de manera selectiva?', 12),
			array(332, 'Los agitadores se encuentran bien ubicados y anclados', 12),
			array(333, '¿Todos los compartimientos cuentan con suficiente agitación?', 12),
			array(334, 'Verificar adecuada operación de todos los agitadores', 12),
			array(335, 'El sistema de circulación cuenta con pistolas de agitación suficientes', 12),
			array(336, '¿Se realizó prueba de las pistolas de agitación?', 12),
			array(337, 'El sistema de circulación permite realizar de manera eficiente, el circuito corto', 12),
			array(338, 'Las escaleras de acceso a los tanques son seguras, ¿ergonómicas?', 12),
			array(339, '¿Señalización para uso de los EPP, se encuentra instalada?', 12),
			array(340, '¿Se dispone de estación lava ojos a máximo 10 segundos del área de riesgo?', 12),
			array(341, 'Verificar condición operativa del Lava ojos', 12),
			array(342, 'El acceso al área del lavaojos está despejado, ¿es segura?', 12),
			array(343, '¿Lava ojos aseado y con agua limpia?', 12),
			array(344, 'Orden y limpieza general del área', 13),
			array(345, 'Adecuada iluminación del área array(Mínimo 150 Lux)', 13),
			array(346, 'Sistema de alumbrado de emergencia disponible', 13),
			array(347, 'Provisión de iluminación aprobada para la locación. Clase I div. II.', 13),
			array(348, 'Guardas de seguridad para partes en movimiento y térmicas instaladas', 13),
			array(349, 'Sistema de puesta a tierra acorde al RETIE', 13),
			array(350, 'Verificar horas de operación desde el último overhaul a los motores y generadores', 13),
			array(351, 'Verificar registros de mantenimiento de motores, generadores y sistema eléctrico', 13),
			array(352, 'Motores diésel sin fugas de aceite, combustible, gases calientes', 13),
			array(353, 'Motores diésel y generadores sin vibraciones, sobre temperaturas ni ruidos anormales', 13),
			array(354, 'Verificar adecuada alineación de generadores y motores diésel', 13),
			array(355, 'Todos los instrumentos del panel de control de cada motor y generador, operativos?', 13),
			array(356, 'Los Shut Downs locales y remotos, se encuentran bien identificados?', 13),
			array(357, 'Los Shut Downs locales y remotos, fueron probados?', 13),
			array(358, 'Adecuada señalización del área, acorde al REITE y la NTC-2050?', 13),
			array(359, 'Señalas visibles de Requisito de protección auditiva', 13),
			array(360, 'Generadores insonorizados?', 13),
			array(361, 'Puertas de acceso bien sujetas, con pasadores', 13),
			array(362, 'Puertas de ingreso al área de generadores libres de obstrucciones', 13),
			array(363, 'Áreas de circulación seguras, demarcadas?', 13),
			array(364, 'Extintores de CO2 disponibles en el área', 13),
			array(365, 'Adecuada ubicación de los extintores, el acceso es seguro?', 13),
			array(366, 'Motores diésel con Flash Arrestor en los escapes?', 13),
			array(367, 'Motores diésel ubicados a más de 100 Ft. Del contrapozo?', 13),
			array(368, 'Cableado eléctrico en buenas condiciones?', 13),
			array(369, 'Cables eléctricos para voltaje superior al de los generadores', 13),
			array(370, 'Salidas eléctricas fuera de uso cubiertas', 13),
			array(371, 'Todos los cables eléctricos debidamente identificados, demarcar el voltaje que manejan?', 13),
			array(372, 'Hay cables eléctricos energizados, tendidos por el suelo', 13),
			array(373, 'Se observan cables de potencia eléctrica empalmados?', 13),
			array(374, 'Empalmes en cables No.12 o mayor para servicio pesado con aislamiento, protección de funda externa y características de uso del cable original', 13),
			array(375, 'Generadores de A.C. con todas sus tapas, bien aseguradas', 13),
			array(376, 'Todos los plugs y receptacles, en buen estado', 13),
			array(377, 'Realizar tomografía de los plugs y receptacles, con carga, para verificar si hay puntos calientes', 13),
			array(378, 'Área de generadores libre de filtraciones o goteras', 13),
			array(379, 'Se dispone de la estación de Lock out y Tag out?', 13),
			array(380, 'Se dispone de procedimiento para Lock out y Tag out? Verificar', 13),
			array(381, 'A todos los breakers y gabinetes, se les puede bloquear y etiquetar?', 13),
			array(382, 'Se dispone de protección térmica ignífuga, sobre los silenciadores de motores diésel?', 13),
			array(383, 'Se dispone de tapete dieléctrico frente a los tableros de control de generadores?', 13),
			array(384, 'Se cuenta con generador de Back up?', 13),
			array(385, 'Manguera de agua para limpieza del área, alejada del área del generador?', 13),
			array(386, 'Los electricistas disponen del reglamentario carnet del CONTE?', 13),
			array(387, 'Los electricistas disponen de capacitación en la norma NFPA 70E?', 13),
			array(388, 'Se realizó prueba en vacío con cada generador?', 13),
			array(389, 'Se realizó prueba de carga a cada generador de A.C.?', 13),
			array(390, 'Verificar registros de inspección NDT Cat. III y Cat. IV , vigentes, para los tanques de aire', 14),
			array(391, 'Verificar registros de mantenimiento de todos los compresores, incluido el Cool star y el secador de aire', 14),
			array(392, 'Verificar orden y aseo en el área de compresores', 14),
			array(393, 'Verificar condición de las áreas de circulación', 14),
			array(394, 'Verificar que todos los tanques de aire dispongan de Relief Valve, acorde a su tamaño', 14),
			array(395, 'Verificar que las Relief valves, no estén pintadas', 14),
			array(396, 'Verificar que la descarga de las Relief Valves, no afecten personas u otros equipos', 14),
			array(397, 'Verificar los TAG de calibración de las relief valves de los tanques de aire array(Vigencia máxima de un año)', 14),
			array(398, 'Verificar que todos los tanques de aire, tengan la placa de certificación ASME sección VIII', 14),
			array(399, 'Verificar adecuada nivelación e instalación de cada compresor array(Tornillos soporte, bien ajustados)', 14),
			array(400, 'Verificar aplicación del código de colores, en las instalaciones del sistema neumático', 14),
			array(401, 'Verificar adecuada señalización de los tanques y líneas neumáticas', 14),
			array(402, 'Verificar adecuado aterrizaje de los motores eléctricos de los compresores, acorde con el RETIE', 14),
			array(403, 'Verificar adecuada señalización del equipo eléctrico, de acuerdo a la NTC-2050', 14),
			array(404, 'Verificar adecuada operación de las check valves, en la descarga de cada compresor', 14),
			array(405, 'Verificar que cada tanque de aire disponga de válvula de corte de aire tanto a la entrada como a la salida del mismo  ', 14),
			array(406, 'Verificar condición general de guardas de seguridad para partes en movimiento y guardas térmicas del manifold de descarga', 14),
			array(407, 'Verificar condición del aceite sintético de cada compresor', 14),
			array(408, 'Verificar correcta operación del panel de control y todos sus instrumentos', 14),
			array(409, 'Verificar adecuada operación de los Shut Downs de cada compresor y del secador de aire del equipo', 14),
			array(410, 'Verificar adecuada iluminación del área de compresores array(Mínimo 150 Lux)', 14),
			array(411, 'Verificar operación de cada compresor y del secador de aire, en vacío y con carga, sin fugas, ruidos, vibraciones o temperaturas anormales', 14),
			array(412, 'Se dispone de un compresor de Back up, capacitado para sostener la demanda de aire de taladro?', 14),
			array(413, 'Verificar normal operación del sistema neumático con todo el equipo operativo', 14),
			array(414, 'Verificar adecuado stock de repuestos en bodega del equipo, para los compresores y secador de aire ', 14),
			array(415, 'Capacidad del Stack de BOPs, acorde con el proyecto array(Tamaño, presión, tipo de lodo, presencia de H2S, presencia de gas)', 15),
			array(416, 'Certificación de todo el Stack de BOPs vigente y en concordancia con API SPECIFIC. 6A y API 16ª', 15),
			array(417, 'Verificar registros de mantenimiento del Stack de BOPs', 15),
			array(418, 'Certificación de todos los Rams en concordancia con el tamaño de tubería a utilizar', 15),
			array(419, 'Tipo de packing unit y certificación del mismo', 15),
			array(420, 'Verificar adecuado stock y almacenamiento de los side Door, Top Seals, packing units y seal Kits, para el Stack de BOPs', 15),
			array(421, 'Verificar adecuada instalación del Stack de BOPs', 15),
			array(422, 'Verificar adecuada estabilización del Stack de BOPs', 15),
			array(423, 'Verificar fecha de última prueba del Stack de BOPs, kill line y choke line', 15),
			array(424, 'Verificar que todo el Stack de BOPs esté en condiciones operativas array(Sin fugas, con todos los pernos B7 y tuercas 2H bien instaladas, bridas bien ajustadas, orden y aseo del área)', 15),
			array(425, 'Todas las líneas hidráulicas que llegan a la BOP, son ignífugas?', 15),
			array(426, 'Todas las líneas hidráulicas están conectadas?', 15),
			array(427, 'Las líneas hidráulicas que no están en uso, disponen de su respectivo tapón?', 15),
			array(428, 'Los volantes para operación manual de las BOPs, se encuentran instalados?', 15),
			array(429, 'Se dispone de parrilla de trabajo y Retráctiles para el montaje seguro del Stack de BOPs    ', 15),
			array(430, 'Se dispone de Pipe Wipers para prevenir la eventual caída de objetos al pozo?', 15),
			array(431, 'El choke line registra restricción alguna al flujo normal', 15),
			array(432, 'Los pernos utilizados en el Kill line como en el choke line, son B7 y tuercas 2H?', 15),
			array(433, 'Todas las válvulas del Kill Line y del Choke line, cuentan con registro de inspección NDT categ. IV vigente', 15),
			array(434, 'Todas las válvulas del Kill Line y del Choke line, tienen instalados sus volantes', 15),
			array(435, 'La choke Hose y Kill line Hose, cumplen con especificación API 7K? array(Certificación del fabriante, Fecha fabricación, W.P., Test Pressure)', 15),
			array(436, 'La Kill line Hose y Choke Line Hose, disponen de adecuada guaya anti látigo?', 15),
			array(437, 'Los radios de giro de la Kill line Hose y Choke Line Hose, son suaves array(en concordancia con la recomendación del fabricante)', 15),
			array(438, 'Todas las válvulas y accesorios utilizados en el Kill Line y Choke Line, con para el Rating de presión igual o superior al del Stack de BOPs?', 15),
			array(439, 'La Kill Line y Choke Line hoses, cuentan con certificación reciente array(Inspección visual, inspección NDT en áreas terminales, Otoscope, prueba hidrostática a la W.P.)', 15),
			array(440, 'En el equipo se cuenta con la herramienta para aplicar el Plastic Packing a las gate valves del Kill Line y choke Line?', 15),
			array(441, 'Verificó que el acumulador tuviera la bandeja ecológica', 16),
			array(442, 'Verificación de la condición correcta de todas las guardas de seguridad sobre elementos rotativos o en movimiento?', 16),
			array(443, 'El acumulador registra fugas de aceite o aire?', 16),
			array(444, 'Verificó que el acumulador tuviera la capacidad suficiente para operar las BOPs tipo Rams y el preventor anular?', 16),
			array(445, 'La instrumentación del acumulador fue verificada por parte de un instrumentista idóneo?', 16),
			array(446, 'Los manómetros patrón, cuentan con calibración vigente?', 16),
			array(447, 'La presión de precarga de las botellas del acumulador, se encuentra entre 950 y 1.047 psi?', 16),
			array(448, 'Verificó adecuada operación de las bombas neumáticas', 16),
			array(449, 'Las bombas neumáticas disponen de strainers en la succión y Check Valve en las descarga?', 16),
			array(450, 'Verificó adecuada operación de la bomba triplex eléctrica', 16),
			array(451, 'Las bomba eléctrica dispone de strainer en la succión y Check Valve en las descarga?', 16),
			array(452, 'Verificó correcta operación del motor eléctrico de 25HP. Que acciona la bomba triplex?', 16),
			array(453, 'Verificó capacidad de sistema neumático, para sostener la operación de las bombas neumáticas?', 16),
			array(454, 'Verificó el libre acceso hacia el acumulador', 16),
			array(455, 'Tiempo para llegar de 0 a 3.000 Psi. Con las bombas neumáticas', 16),
			array(456, 'Tiempo para llegar de 0 a 3.000 Psi. Con la bomba eléctrica', 16),
			array(457, 'Tiempo para llegar de 0 a 3.000 Psi. Con las bombas neumáticas y la bomba eléctrica', 16),
			array(458, 'Bombas neumáticas arrancan a 2.500 Psi.', 16),
			array(459, 'La bomba eléctrica arranca a 2.750 Psi.', 16),
			array(460, 'El tanque de aceite dispone de visor de nivel?', 16),
			array(461, 'El aceite del acumulador está limpio?', 16),
			array(462, 'El regulador manual para el manifold, está operando correctamente?', 16),
			array(463, 'El regulador de presión TRL-5 para el preventor anular, está operando  bien?', 16),
			array(464, 'El acumulador dispone de doble válvula de seguridad?', 16),
			array(465, 'La válvula de seguridad del acumulador está ajustada a 3.350 Psi.', 16),
			array(466, 'La válvula de seguridad del manifold del está ajustada a 3.300 Psi.', 16),
			array(467, 'El acumulador dispone de alarma por bajo nivel de aceite en el tanque, de tipo lumínica y sonora', 16),
			array(468, 'El acumulador dispone de alarma por baja presión de aceite, de tipo lumínica y sonora?', 16),
			array(469, 'La válvula de By-Pass del manifold, está operativa?', 16),
			array(470, 'Los registros de inspección NDT de las botellas del acumulador y del manifold, están vigentes y disponibles en el equipo', 16),
			array(471, 'La última prueba hidrostática de las botellas del acumulador, tiene cinco o más años?', 16),
			array(472, 'La señalización de seguridad del acumulador es adecuada', 16),
			array(473, 'Las válvulas selectoras de cuatro vías, tres posiciones del manifold, registran fuga?', 16),
			array(474, 'La válvula de cuatro vías, tres posiciones, de operar los Blind Rams, está cubierta para prevenir su accidental acción?', 16),
			array(475, 'Las mangueras del acumulador a la BOP, son de tipo IGNÍFUGO?', 16),
			array(476, 'El operador remoto ubicado en la casa del perro, se encuentra operativo?', 16),
			array(477, 'En el remoto del acumulador se pueden visualizar todas las presiones del acumulador?', 16),
			array(478, 'Se realizó prueba operativa del acumulador, utilizando el Stum Test array(Prueba Off Line), alineado con el Stack de BOPs, para verificar eficiencia hidráulica y comprobar que no hay fugas?', 16),
			array(479, 'Se dispone de extintor de incendios apropiado en el área del acumulador, acorde al volumen de aceite almacenado', 16),
			array(480, 'La señalización de seguridad del acumulador esta en concordancia con el sistema globalmente armonizado?', 16),
			array(481, 'Hay señales de  advertencia visibles, de operación automática del acumulador?', 16),
			array(482, 'Certificación de todo el choke manifold vigente y en concordancia con API SPECIFIC 6A, API 16A, RP-53, RP54', 17),
			array(483, 'Verificar registros del último mantenimiento realizado al choke manifold', 17),
			array(484, 'Verificar operación suave de todas y cada una de las válvulas del choke manifold', 17),
			array(485, 'Verificar registros de la última inspección NDT categ. IV, realizada al choke manifold, registrar fecha', 17),
			array(486, 'Verificar registros de la última inspección NDT categ. III, realizada al choke manifold, registrar fecha', 17),
			array(487, 'Verificar adecuado stock de repuestos para las gate valves, los chokes y operador remoto del choke', 17),
			array(488, 'Verificar adecuada instalación del choke manifold array(anclaje con grapas de seguridad integrales, al skid, aseguradas con tornillos grado 8)', 17),
			array(489, 'Verificar fecha de última prueba del Choke Manifold', 17),
			array(490, 'Verificar adecuada apertura y cierre de cada uno de los chokes', 17),
			array(491, 'Verificar último registro de revisión de la instrumentación del choke manifold y del operador remoto del choke hidráulico', 17),
			array(492, 'Los manómetros para indicar D.P. Pressure y Casing Pressure, deben tener carátula de 6 y subdivisiones de 20 psi', 17),
			array(493, 'Los pernos utilizados en el choke manifold, son B7 y tuercas 2H', 17),
			array(494, 'Todas las válvulas del choke manifold, tienen instalados sus volantes', 17),
			array(495, 'Todas las válvulas del choke manifold, están marcadas y se identifica si están abiertas o cerradas claramente?', 17),
			array(496, 'La Panic Line registra algún estrangulamiento en su trayecto', 17),
			array(497, 'La salida de la Panic Line es recta?', 17),
			array(498, 'Todas las válvulas y accesorios utilizados en el choke manifold, son para el rating de presión igual o superior al del Stack de BOPs?', 17),
			array(499, 'Las válvulas y chokes, son del mismo PSL?', 17),
			array(500, 'En el equipo se cuenta con la herramienta para aplicar el Plastic Packing a las gate valves del choke manifold?', 17),
			array(501, 'Se dispone de certificación vigente ASME sección VIII de la vasija Poor Boy', 17),
			array(502, 'Fecha de última inspección NDT del Poor Boy', 17),
			array(503, 'El diseño e instalación del Poor Boy, cumple con la especific. API 12J?', 17),
			array(504, 'El  Poor Boy dispone de Relief valve?', 17),
			array(505, 'La línea de venteo es de diámetro acorde al volumen de gas a quemar?', 17),
			array(506, 'La línea de venteo registra pocas curvas?', 17),
			array(507, 'La línea de venteo se encuentra debidamente anclada?', 17),
			array(508, 'La tea está ubicada en área segura, retirada de materiales u objetos susceptibles de encender', 17),
			array(509, 'La tea está ubicada a la altura reglamentaria, establecida en el PMA?', 17),
			array(510, 'Se dispone de al menos dos sistemas de encendido diferentes para la Tea', 17),
			array(511, 'La tea se encuentra debidamente estabilizada', 17),
			array(512, 'La tea dispone de bandeja ecológica acorde a su altura?', 17),
			array(513, 'Se dispone de válvula de drenaje de condensados, en la sección inferior de la Tea?', 17),
			array(514, 'Se realizó prueba de correcta operación de la Tea?', 17),
			array(515, 'La tubería y uniones de golpe de la Tea, disponen de inspección NDT reciente?', 17),
			array(516, 'La línea de la tea está debidamente señalizada y protegida en caso de circulación de vehículo?', 17),
			array(517, 'El acceso al MCC tiene señalización de riesgo eléctrico y restricción para acceso a personal no autorizado?', 18),
			array(518, 'El acceso al MCC está libre de obstáculos', 18),
			array(519, 'El MCC está aseado y ordenado?', 18),
			array(520, 'Se dispone de sistema de alumbrado de emergencia?', 18),
			array(521, 'El piso del MCC, es dieléctrico?', 18),
			array(522, 'Tiene debidamente señalizada la tensión de servicio y la corriente nominal?', 18),
			array(523, 'Tiene señalizado el número de fases?', 18),
			array(524, 'El interior del tablero, todos y cada uno de los interruptores, están debidamente identificados?', 18),
			array(525, 'El tablero está montado dentro de cajas, gabinetes o armarios?', 18),
			array(526, 'El tablero está construido con materiales no Higroscópicos array(Que no liberen humedad) ni combustibles?', 18),
			array(527, 'El tablero es resistente a la corrosión, o está protegido contra ella?', 18),
			array(528, 'El tablero es hermético, de acceso frontal, se puede mantener cerrado?', 18),
			array(529, 'Posee luces piloto que indiquen el funcionamiento de cada una de las fases?', 18),
			array(530, 'El tablero posee tapa interior dieléctrica que impida el contacto con partes energizadas?', 18),
			array(531, 'El tablero está posicionado entre 0.6 y 2 mts. De altura, desde el nivel del piso?', 18),
			array(532, 'El aterrizaje del MCC está acorde con el RETIE?', 18),
			array(533, 'Se dispone de estación Lock Out  Tag Out', 18),
			array(534, 'Todas las secciones del MCC, están operativas?', 18),
			array(535, 'El indicador de falla a tierra del MCC está opeativo?', 18),
			array(536, 'Todos los controles de operación, breakers, protecciones térmicas, protecciones magnéticas y contactores del MCC están operativos?', 18),
			array(537, 'Las protecciones termomagnéticas de los motores de A.C. están acordes a su capacidad?', 18),
			array(538, 'El tablero dispone de interruptores diferenciales array(10mA. Para 220V. monofásicos, 30 mA. Para 480 V.trifásicos)', 18),
			array(539, 'Los aires acondicionados están operativos?', 18),
			array(540, 'La iluminación del MCC, es adecuada?', 18),
			array(541, 'Las puertas de acceso al MCC cierran adecuadamente?', 18),
			array(542, 'El MCC dispone de chapas anti pánico tanto en el ingreso como en la salida?', 18),
			array(543, 'La caseta del MCC presenta filtraciones o humedad?', 18),
			array(544, 'El panel de salida de conexiones de A.C. está aseado, señalizado, operativo?', 18),
			array(545, 'El panel de salida de conexiones de A.C. está protegido de la humedad?', 18),
			array(546, 'La lámpara externa de detección de falla a tierra, está operativa', 18),
			array(547, 'El transformador de 480  220 volt. Para A.C. del equipo está operativo?', 18),
			array(548, 'La estación del Rig Intercom array(si la hay), se encuentra oerativa?', 18),
			array(549, 'El extintor de Halon o CO2, está en buenas condiciones, cargado y bien ubicado?', 18),
			array(550, 'La alarma para detección de humo, está operativa?', 18),
			array(551, 'Se comprobó el adecuado funcionamiento de los dispositivos diferenciales, así como el tiempo y la intensidad del disparo, registrando los valores.', 18),
			array(552, 'En el equipo se dispone de los manuales de partes, operación y mantenimiento del equipo eléctrico?', 18),
			array(553, 'El personal de mantenimiento es idóneo  el electricista cuenta con el carnet del consejo Nacional de Técnicos Electricistas CONTE?', 18),
			array(554, 'Los electricistas y personal de mantenimiento, cuentan con capacitación en la norma NFPA-70E?', 18),
			array(555, 'El SCR está aseado y ordenado?', 19),
			array(556, 'Se dispone de estación lock out  tag out', 19),
			array(557, 'Se dispone de sistema de alumbrado de emergencia', 19),
			array(558, 'El piso del SCR, es dieléctrico?', 19),
			array(559, 'Se dispone de adecuada señalización de seguridad, acorde al RETIE y la NTC-2050?', 19),
			array(560, 'Todas las secciones del SCR, están operativas?', 19),
			array(561, 'Indicador de falla a tierra del SCR está operativo?', 19),
			array(562, 'Todos los controles de operación, breaker, protecciones, del SCR, están operativos?', 19),
			array(563, 'El banco de resistencias del freno dinámico del malacate está operando correctamente?', 19),
			array(564, 'Los indicadores de falla a tierra de motores del malacate y las bombas de lodo están operativos?', 19),
			array(565, 'Las dos unidades centrales de aire acondicionado están operativas?', 19),
			array(566, 'Los indicadores del bus principal de A.C. de 600 volt. Y el sincronoscópio de los generadores están operativos', 19),
			array(567, 'Las diferentes asignaciones para la correcta operación de las bahías de los SCRs, están en buen estado y operativas?', 19),
			array(568, 'Las diferentes bahías del SCR están operativas?', 19),
			array(569, 'La iluminación dentro del SCR, es adecuada?', 19),
			array(570, 'La lámpara externa de detección de falla a tierra, está operativa?', 19),
			array(571, 'Las puertas de acceso y salida del SCR, están libres de obstáculos o condiciones inseguras?', 19),
			array(572, 'El SCR dispone de chapas anti pánico?', 19),
			array(573, 'Los lock out manual de los motores eléctricos del malacate y de las bombas de lodo dentro del SCR están operativos?', 19),
			array(574, 'Los breakers de 1.600 amp. De las bahías y los generadores de A.C., están certificados?', 19),
			array(575, 'Se probaron todos los breakers de 1600 amp. Del SCR?', 19),
			array(576, 'La caseta del SCR presenta filtraciones o humedad?', 19),
			array(577, 'Las puertas de acceso al SCR cierran adecuadamente?', 19),
			array(578, 'El transformador de 600  480 volt para A.C. del equipo están operativo?', 19),
			array(579, 'El transformador de 600  220/120 volt para iluminación del equipo están operativo?', 19),
			array(580, 'Los transformadores de 600  220 volt para alimentación del campamento, están operativos?', 19),
			array(581, 'El barraje de entrada A.C. a las bahías está en buen estado?', 19),
			array(582, 'Los barrajes de salida de cada una de las bahías están operativas', 19),
			array(583, 'Las salidas eléctricas fuera de uso están cubiertas?', 19),
			array(584, 'Todos los cables eléctricos están debidamente identificados demarcar el voltaje que manejan?', 19),
			array(585, 'Todos los plugs y receptacles, están en buen estado?', 19),
			array(586, 'El panel de salida de conexiones de A.C. y D.C. están aseados, señalizados y operativos?', 19),
			array(587, 'El deshumidificador del SCR está operativo?', 19),
			array(588, 'La estación del Rig Intercom, se encuentra operativa?', 19),
			array(589, 'Se dispone de un bastón de pastor array(Gancho dieléctrico), en el SCR?', 19),
			array(590, 'El electricista cuenta con guantes dieléctricos certificados, con careta dieléctrica y herramienta aislada', 19),
			array(591, 'El extintor de Halon o CO2, está en buenas condiciones, cargado y bien ubicado?', 19),
			array(592, 'La alarma para detección de humo, esta operativa?', 19),
			array(593, 'La alarma por alta temperatura en el cuarto, esta operativa?', 19)
        );

        foreach($data as $row){
	        DB::table('review_categories')->insert([
	            'id' => $row[0],
	            'name' => $row[1],
	            'category' => $row[2]
	        ]);
    	}
    }
}
